### ISSUE TITLE
Pong example not properly working

### ISSUE THREAD

**Issue by beef331** [beef331/nettyrpc#2]
Allows a user to join and will send the name, but the paddle does not update position, could possibly be because the new relayed logic does not check the source of the packet and sends it to everyone, needs to be investigated and fixed.

After further testing seems to be purely random what works, sometimes ball will not sync, othertimes paddle.

**Comment by RattleyCooper** [comment]
I will investigate after work.

**Comment by beef331** [comment]
Ah investigating the issue is everything is traced back to rpcTick, first you read the managed ID, which moves the stream position, then you read the relayed id, then breakafter relaying, so at most 1 procedure can run.

**Comment by RattleyCooper** [comment]
> Ah investigating the issue is everything is traced back to rpcTick, first you read the managed ID, which moves the stream position, then you read the relayed id, then breakafter relaying, so at most 1 procedure can run.

Yep, that's what I'm finding out as well.  

>Moving while loop into for msg in reactor.messages loop and processing each message's stream separately helps fix some sync issues but there is still some sync issues that need to be worked out. Likely related to the relay proc not updating all the _appropriate_ clients.

**Comment by beef331** [comment]
Ah actually they use two different buffers, so I'm wrong.

**Comment by RattleyCooper** [comment]
> If the managed ID isnt there you need to move the pos of the stream back `int` bytes so that it can then read the appropriate data.

Gotcha

>Ah actually they use two different buffers, so I'm wrong.

No, you're still correct because it still breaks.

**Comment by RattleyCooper** [comment]
>Does the relayed even need the conection parameter, since it should just send it to all users other than that it recieved it from(if it's the server), otherwise it doesnt care the connection when running the procedure?

I pass the connection in so it knows which connection to ignore when sending the relay

**Comment by beef331** [comment]
I am talking about `relayedEvents*: array[uint16, proc(data: var NettyStream, conn: Connection)]`, this is used just to invoke the internal procedure, why does it even need connection?

**Comment by RattleyCooper** [comment]
> I am talking about `relayedEvents*: array[uint16, proc(data: var NettyStream, conn: Connection)]`, this is used just to invoke the internal procedure, why does it even need connection?

You're totally correct, it does not technically need the connection, especially since the Connection will always refer to the server on the client's end and is useless for the server to have.

**Comment by beef331** [comment]
So the list of things that need to be fixed are server needs to relay to all clients, need to stop breaking after managed/relayed events. Looking at it now, we really should put a messageType at the start of the packets so we dont need to have this weird while loop, so then we add only messages that corespond to the buffers to the buffers.

**Comment by RattleyCooper** [comment]
> So the list of things that need to be fixed are server needs to relay to all clients, need to stop breaking after managed/relayed events. Looking at it now, we really should put a messageType at the start of the packets so we dont need to have this weird while loop, so then we add only messages that corespond to the buffers to the buffers.

So, even with a messageType being added to the beginning of the message we still have to use the while loop on the buffer, and we have to process the entire buffer.  This is because the local procedures write to the sendBuffer and the sendBuffer is sent every rpcTick.  The server relays the sendBuffer that contains multiple messages but the clients are not processing the entire data stream.

`relayed` macro rewrites the procs like so: 

```nim
proc updatePaddle(p: Paddle; isLocal: bool = true) =
  if (not isLocal):
    for x in paddles.mitems:
      if (not x.local):
        x.y = p.y
  if isLocal:
    write(sendBuffer, MessageType.Relayed)
    write(sendBuffer, 2'u16)
    write(sendBuffer, p)

proc updateBall(inBall: Ball; isLocal: bool = true) =
  ball = inBall
  if isLocal:
    write(sendBuffer, MessageType.Relayed)
    write(sendBuffer, 3'u16)
    write(sendBuffer, inBall)
```

You can see how the messages add up in the buffer, but `rpcTick` doesn't process the entire buffer

**Comment by beef331** [comment]
Well of course the while loop is used, you can have more than a single proc call in a message, by weird while loop I meant one with indecisiveness. This removes this by making it so you know which type of proc you got, so you can just handle it accordingly.

**Comment by RattleyCooper** [comment]
> Well of course the while loop is used, you can have more than a single proc call in a message, by weird while loop I meant one with indecisiveness. This removes this by making it so you know which type of proc you got, so you can just handle it accordingly.

Ok gotcha.  I'm making good progress.  Have the pong example working with messages being dispatched based on a `MessageType`.  I'm going to work up an authoritative server example based on the pong example and make sure I didn't break anything else.

One thought though.  The `rpc` procedures send the `sendBuffer` when they're called instead of writing to the `sendBuffer` and sending the entire buffer in the `rpcTick` procedure.  This was originally done to make it easy for the server to send an RPC to all connected clients, or a single client.  I'm not sure if sending when the `rpc` procedures are called is better or worse than writing to the buffer and sending the entire buffer.  Thoughts?

**Comment by beef331** [comment]
It's best to send a single large message than a bunch of smaller messages, especially since every frame(atleast in the pong example) there will be a tick. This way we can reduce the network traffic over time and minimize network usage(small packets also contain the netty reliable UDP logic).

**Comment by RattleyCooper** [comment]
Ok, I will incorporate a separate buffer for sending to all clients and move all the sending logic from the `rpc` procedures over to `rpcTick`.

**Comment by RattleyCooper** [comment]
I may end up just doing separate `tick` procedures.  1 for relaying and 1 for authoritative servers.  Sure, people won't be able to mix the 2 together but tbh that may be better anyway.  It's just getting to be a huge pain making them both work with the same `tick` procedure.

**Comment by beef331** [comment]
I dont quite follow why it's an issue, could you push the code somewhere so I could take a look?

**Comment by RattleyCooper** [comment]
Well I really wanted to support direct sending to a specific client so that an RPC doesn't necessarily have to go out to every single client if it isn't needed.  In `rpcTick` the data stream is written to the buffer:

```nim
for msg in reactor.messages:
  theBuffer.addToBuffer(msg.data)

while (not theBuffer.atEnd):
  # Dispatch local RPC but networked RPC requires access to the msg.conn Connection object for direct sending.
```

And there is no way to track the connection that sent the message unless we process the stream as it's being read, or unless we include some kind of connection id.  netty doesn't sync connection id's or anything like that so I am having a lot of trouble figuring out how the server is going to handle sending RPCs to specific clients instead of all clients.

Here is my current `rpcTick`:

```nim
proc rpcTick*(sock: Reactor, server: bool = false) =
  ## Parses all packets recieved since last tick.
  ## Invokes procedures internally.  If no procedure is
  ## found it will relay the command.
  sock.tick()
  if not server:
    client.send(sendBuffer)

  var theBuffer = NettyStream()
  var conn: Connection # CLIENT-SIDE IS ALWAYS RECEIVING FROM THE SERVER!
  for msg in reactor.messages:
    theBuffer.addToBuffer(msg.data)
    conn = msg.conn  # Since the connection is always the server this is safe for client.  Used for relay

  while(not theBuffer.atEnd):
    let messageType = block:  # Read the message type
      var res: MessageType
      theBuffer.read res
      res

    case messageType:
    of MessageType.Relayed:
      if server:
        relayServerTick()
        return
      let relayedId = block:
        var res: uint16
        theBuffer.read res
        res
      if(relayedEvents[relayedId] != nil):
        relayedEvents[relayedId](theBuffer)
    of MessageType.Networked:
      # Logic for networked RPC if we have access to Connection
      raise newException(NettyRpcException, "Networked messages mixed with relayed messages.  Don't mix relayed and networked pragmas.")
```

**Comment by RattleyCooper** [comment]
I think I have a working solution for reading a partial data stream for networked procs.  It seems kind of hacky but it does work.  It tries to read the data stream and if it can't then it breaks out of the while loop and adds to the buffer and tries again.

```nim
proc networkTick*(sock: Reactor, server: bool = false) =
  sock.tick()
  if server:
    for k, s in directSends.pairs:
      var directSendStream = NettyStream()
      for stream in s:
        directSendStream.addToBuffer(stream.getBuffer)
      reactor.send(k, directSendStream.getBuffer)
    directSends.clear()
  sendall(sendAllBuffer)

  var theBuffer = NettyStream()
  var theBufferPos = theBuffer.pos
  for msg in reactor.messages:
    # echo "got message"
    theBuffer.addToBuffer(msg.data)
    block blockBuster:
      while(not theBuffer.atEnd):
        let messageType = block:  # Read the message type
          var res: MessageType
          try:
            theBuffer.read res
          except RangeDefect:
            break blockBuster  # break out of while loop.
          res

        case messageType:
        of MessageType.Networked:
          let managedId = block: 
            var res: int
            theBuffer.read res
            res
          if managedEvents.hasKey(managedId):
            managedEvents[managedId](theBuffer, msg.conn)
        of MessageType.Relayed:
          raise newException(NettyRpcException, "Relayed messages mixed with networked messages.  Don't mix relayed and networked pragmas.")
```
I think I can merge this with the normal `rpcTick` procedure without much trouble.

**Comment by beef331** [comment]
`except RangeDefect:` This is bad form, defects are not to be caught they're to be avoided. What's the issue with putting RPC inline with relayed? Doesnt the RPC only call on the server then the server reasons to who to send any resultant action?

**Comment by RattleyCooper** [comment]
> What's the issue with putting RPC inline with relayed? Doesnt the RPC only call on the server then the server reasons to who to send any resultant action?  

I'm not sure I follow what you mean about inlining with relayed.  With the authoritative approach the client can send an RPC to the server which runs a local procedure and the server can also send an RPC directly to a client or to all clients, which run their own procedures.

**Comment by beef331** [comment]
The rpc message is like `MessageKind.Networked, networkedID, params` it doesnt have a target built into the message, if you want to send it to a specific client it's up to the server to reason that, as such it can be stored with the relayed messages assuming your relayed messages are written as such `MessageKind.Relayed, lengthOfRelayedMessageinBytes,relayedMessages(all of them together)`

**Comment by beef331** [comment]
The following is what i'm suggesting, might make it more clear
```nim
proc networkTick*(sock: Reactor, server: bool = false) =
  sock.tick()
  if server:
    for k, s in directSends.pairs:
      var directSendStream = NettyStream()
      for stream in s:
        directSendStream.addToBuffer(stream.getBuffer)
      reactor.send(k, directSendStream.getBuffer)
    directSends.clear()
  sendall(sendAllBuffer)

  var theBuffer = NettyStream()
  var theBufferPos = theBuffer.pos
  for msg in reactor.messages:
    # echo "got message"
    theBuffer.addToBuffer(msg.data)
      while(not theBuffer.atEnd):
        let messageType = block:  # Read the message type
          var iVal: uint8
           theBuffer.read iVal
           if iVal in MessageType.low.ord .. MessageType.high.ord:
             MessageType(iVal)
           else:
              break # We've got a wrong message

        case messageType:
        of MessageType.Networked:
          let managedId = block: 
            var res: int
            theBuffer.read res
            res
          if managedEvents.hasKey(managedId):
            managedEvents[managedId](theBuffer, msg.conn)
        of MessageType.Relayed:
          let messageLength = block:
            var res: int
            theBuffer.read res
          while theBuffer.getPosition < messageLength:
             # Treat like a relayed message
```

**Comment by RattleyCooper** [comment]
How would you getting the message size?  I'm doing it in the macro but not sure if this is a good way to go about it.  Ends up with a proc that creates a temporary netty stream every time a relayed proc is called so I can calculate the size of the message:

```nim
proc ballScored(leftScr, rightScr: int; isLocal: bool = true) =
  leftScore = leftScr
  rightScore = rightScr
  if isLocal:
    var tempStream = NettyStream()
    write(tempStream, MessageType.Relayed)
    write(tempStream, 3'u16)
    write(tempStream, leftScr)
    write(tempStream, rightScr)
    var msgLen = sizeof tempStream.getBuffer
    msgLen += sizeof msgLen
    write(sendBuffer, MessageType.Relayed)
    write(sendBuffer, msgLen)
    write(sendBuffer, 3'u16)
    write(sendBuffer, leftScr)
    write(sendBuffer, rightScr)
```

**Comment by beef331** [comment]
This goes to my suggestion of having a relayed buffer, you write all the messages to that then when you go to send you appened the relay buffer to the message contigiously.

**Comment by RattleyCooper** [comment]
I think I might be confused or just have information overload or something. 

I was thinking about this and it seems pretty trivial to create a relay using the `networked` pragma:

```nim
# Server-side authoritative relay
proc doRelay(procName: string, theArgs: tuple) {.networked.} =
  rpc(procName, theArgs)
```

and then convert the `relayed` pragma to simply call the `rpc` proc:

```nim
proc ballScored(leftScr, rightScr: int; isLocal: bool = true) =
  leftScore = leftScr
  rightScore = rightScr
  if isLocal:
    rpc("doRelay", (procName: "ballScored", leftScr: leftScr, rightScr: rightScr, isLocal: isLocal))
```

This would get rid of the requirement for MessageType and the MessageLenth since we are only dealing with 1 type of message, and makes the entire project easier to maintain because we're not having to decipher all this extra stuff.

Thoughts?  lmk if I'm overlooking something.  My brain feels like a potato today.

**Comment by beef331** [comment]
We can go with this assuming you automate the sending of that tuple/message(and also use a static ID), I was planning on swapping to disruptek's frosty anywho(though with an enum bug the nico test fails).

**Comment by RattleyCooper** [comment]
> We can go with this assuming you automate the sending of that tuple/message(and also use a static ID), I was planning on swapping to disruptek's frosty anywho(though with an enum bug the nico test fails). 

Sick, I'll proceed with this route.

>That's not an issue with netty stream, that just invalid code, `b: tuple` is a generic, not a concrete type.

That's really good to hear because I was super stoked to figure out a potential way to simplify this.  So I'll need to use the `thing.type` in the `recBody` of the macro to set up receiving properly.

**Comment by RattleyCooper** [comment]
@beef331 

Am I missing something else when trying to read tuples?

```nim
  test "tuple":
    let a = (a: 1, b: 1.0, c: -1)
    var ns = NettyStream()
    ns.write(a)
    ns.pos = 0
    var b: a.type  # Type mismatch error
    ns.read(b)
    assert a.b == b.b
```

**Comment by beef331** [comment]
Ah actually nettystream doesnt support tuples, even more reason for that move to frosty.

**Comment by RattleyCooper** [comment]
I mean, could I dynamically generate `read` procs that accept a concrete tuple type in the meantime?

**Comment by beef331** [comment]
Eh just use the updated code for nettystreams it was a simple add to generic, cause i guess we dont want to break this for stable Nim presently, since frosty requires devel.

**Comment by RattleyCooper** [comment]
Oh sweet, that is way easier 🎉  I thought there was some kind of limitation.  I was looking at the `write` proc you had that handled tuples and totally forgot to look for the `read` proc.

**Comment by RattleyCooper** [comment]
@beef331 Do you know how to get the concrete tuple type in a macro?  I need to evaluate the `theArgsType` NimNode(a nnkTupleClassTy) so I can use the concrete type in the `recBody`.


```nim
proc relay(procName: string; theArgs: tuple; conn: Connection = Connection()) =
  var theArgsType = type(theArgs)           # Need the value from this in the anonymous proc.
  rpc(procName, theArgs)

managedEvents[4038518758] = proc (data: var NettyStream; conn: Connection) =
  let procName = block:
    var temp`gensym71: string
    data.read(temp`gensym71)
    temp`gensym71
  let theArgs = block:
    var temp`gensym72: tuple         # invalid type `tuple` for var / Need to fill in with type from `theArgsType`, or something similar
    data.read(temp`gensym72)
    temp`gensym72
  relay(procName, theArgs, conn)
```

Do you know of any way to get the concrete tuple type into the anonymous proc being used so I can read data into that `temp` var?

**Comment by beef331** [comment]
You'll need to emit the tuple type constructor ie `(bool, string, float,...)`.

**Comment by RattleyCooper** [comment]
> You'll need to emit the tuple type constructor ie `(bool, string, float,...)`.

I'm not sure how to emit it though.  It doesn't look like I have access to that information in the AST.  Is it possible to use an `ident` to get that information from the `theArgs` tuple?

**Comment by beef331** [comment]
Isnt it just the ident defs stored in the proc parameter list? So `procDef[3][1..^1]` would be the types to go inside a `tupleTy`.

**Comment by RattleyCooper** [comment]
I'm not using a concrete tuple type in the proc def for the `relay`

```nim
proc relay(procName: string; theArgs: tuple; conn: Connection = Connection()) =
  var theArgsType = type(theArgs)
  rpc(procName, theArgs)
```

**Comment by beef331** [comment]
Correct but you are for the proc you have `{.relayed.}` on.

**Comment by RattleyCooper** [comment]
`relay` is the `{.networked.}` proc I want to use to support the `{.relayed.}` proc

**Comment by beef331** [comment]
Here is an example of what I mean:
```nim
import std/macros

macro relayed(a: untyped) =
  result = newStmtList(a)
  result.add newCall(ident"echo", nnkTupleTy.newTree(a.params[1..^1]))
  
proc doStuff(a, b, c: int, d: float) {.relayed.} = discard
```

**Comment by RattleyCooper** [comment]
Well the `relay` proc still needs to read data sent from the client, since it's a server-side RPC.  The client needs to send the RPC they want relayed along with a `tuple` of args that should go with it.  `relay` needs to handle any arbitrary tuple.

Right now the nettyrpc.nim script won't compile because I don't have a concrete tuple type to read data in with.  The relayed RPCs don't exist server-side so I don't have any of the proc defs to work with.

**Comment by beef331** [comment]
This is where i think you need an ID/packet size cause when you send a message to relay the server shouldnt need to do anything but take the message and pass it a long.

**Comment by RattleyCooper** [comment]
Well  that is what the `relay` proc is for.   `relay` is a server-side RPC that would do nothing more than forward the message to all the other clients.

**Comment by beef331** [comment]
Ok push the code and let me take a look at it, so I can actually formulate an idea/plan.

**Comment by RattleyCooper** [comment]
Ok, headed home and I'll get it pushed here in a few minutes.

**Comment by RattleyCooper** [comment]
https://github.com/RattleyCooper/nettyrpc-1/blob/master/src/nettyrpc.nim

**Comment by beef331** [comment]
I've got most of the logic implemented on https://github.com/beef331/nettyrpc/tree/fixings though presently there is an issue with the data, it causes multiple out of range errors. It was not viable to be able to encode the information for a relay any other way in my view, so we have a second buffer for relayed events.

**Comment by RattleyCooper** [comment]
Does this actually write the length of the buffer?

```nim
sendBuffer.write(relayBuffer.getBuffer) # Writes len, message
```

**Comment by beef331** [comment]
Yea the length is written, we dont worry about the size of the header cause on clients we  read id, length then the buffer. so the length doesnt count the id/length. `lent` is just "borrow the memory if possible", it's the read only variant of `var T`.

**Comment by RattleyCooper** [comment]
How is the message length written though?  Doesn't `theBuffer.getBuffer` only write a string?

**Comment by beef331** [comment]
Look at the nettystream write string implementation, all will be revealed.
